- platform: template
  sensors:
    people_home:
      friendly_name: "Home"
      device_class: occupancy
      #entity_id:
      #- input_select.reuben_status_dropdown
      #- input_select.sarah_status_dropdown
      value_template: >-
        {{
          is_state('input_select.reuben_status_dropdown', 'Home')
          or is_state('input_select.sarah_status_dropdown', 'Home')
        }}

#- platform: ring
