- platform: yr

#- platform: ring

- platform: ups
  username: !secret ups_user
  password: !secret ups_password

- platform: fedex
  username: !secret fedex_user
  password: !secret fedex_password

- platform: uptime
  name: ha_uptime
  unit_of_measurement: minutes

#- platform: pi_hole

- platform: template
  sensors:
#    reuben_status:
#      value_template: '{{ states.input_select.reuben_status_dropdown.state }}'
#      friendly_name: 'Reuben'
#      entity_id: input_select.reuben_status_dropdown

#    sarah_status:
#      value_template: '{{ states.input_select.sarah_status_dropdown.state }}'
#      friendly_name: 'Sarah'
#      entity_id: input_select.sarah_status_dropdown

    frontdoorlockbattery:
      #entity_id: zwave.schlage_be469nxcen_touchscreen_deadbolt
      value_template: "{{ states.zwave.schlage_be469nxcen_touchscreen_deadbolt.attributes.battery_level }}"
      friendly_name: 'Front Door Lock Battery'
      unit_of_measurement: '%'

    front_door_code:
      friendly_name: Front Door Last Code
      #entity_id:
      #- sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type
      #- sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level
      value_template: >-
        {% if is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type', '18') or is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type', '19') %}
          {% if not is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level', '0') %}
            {{states('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level')}}
          {% else %}
            {# just provide previous value if no user code entered #}
            {{states('sensor.front_door_code')}}
          {% endif %}
        {% else %}
          {# just provide previous value if no user code entered #}
          {{states('sensor.front_door_code')}}
        {% endif %}

    front_last_action:
      friendly_name: Front Door Last Action
      #entity_id:
      #- sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type
      #- sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level
      value_template: >-
        {% if is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type', '18') %}
          {% if is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level', '0') %}
            Locked: Outside Keypad
          {% else %}
            Locked: User {{states('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level')}}
          {% endif %}
        {% elif is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type', '19') %}
          Unlocked: User Code {{states('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level')}}
        {% elif is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type', '21') %}
          Locked: {{[ 'Outside Lock', 'Inside Deadbolt', 'Outside Keypad' ][states('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level')|int]}}
        {% elif is_state('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type', '22') %}
          Unlocked: Inside Deadbolt
        {% else %}
          Unknown: {{states('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_type')}}/{{states('sensor.schlage_be469nxcen_touchscreen_deadbolt_alarm_level')}}
        {% endif %}
